#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"

SCAN_STATUS_FILE=${PROJECT_ROOT}/statuses/bluetooth-last-scan-status.json

bluetoothctl --timeout 10 scan on | grep NEW | jq -R -s -c '.[:-1] | split("\n")' > ${SCAN_STATUS_FILE}