#!/usr/bin/env bash
set -euo pipefail

die () {
    printf '%s\n' >&2 "$@"
    exit 1
}

[ "$#" -eq 2 ] || die "2 arguments required, $# provided"

command="$1"
mac="$2"

[[ "${command}" =~ ^[a-zA-Z]*$ ]] || die "Invalid command"

[[ "${mac}" =~ ^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$ ]] || die "Invalid mac address"

bluetoothctl "${command}" "${mac}"