#!/usr/bin/env bash
set -euo pipefail

# Start Pi Controller

check_dependencies () {
  for cmd in "$@"; do
    if ! command -v $cmd >/dev/null 2>&1; then
      echo "This script requires \"${cmd}\" to be installed"
      exit 1
    fi
  done
}

# Check system's dependencies
check_dependencies readlink dirname ip

# Check karen's dependencies
check_dependencies fswatch

# Check OTA update scripts' dependencies
check_dependencies rsync jq curl tr

# Check API V1 manager dependencies
check_dependencies yarn node nohup

PROJECT_ROOT="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.."
PROJECT_LOGS="${PROJECT_ROOT}/logs"

#export $(grep -v '^#' "${PROJECT_ROOT}/".env | xargs)

while IFS= read -r line; do
  export "${line?}"
done <"${PROJECT_ROOT}/".env

echo
echo "======================================"
echo "============= STARTING ==============="
echo "=========== PI CONTROLLER ============"
echo "======================================"
echo

echo "Setting environment variables..."
echo

# Whitelist device IP, hostname and hidden service for CORS
DEVICE_IP="$(ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')"
DEVICE_HOSTNAME="$(hostname)"

cd "$PROJECT_ROOT"

echo "Starting karen..."
echo
./scripts/karen "${EVENTS_PATH}" &>> "${PROJECT_LOGS}/karen.log" &

echo "Starting status monitors..."
pkill -f ./status-monitor || true
./scripts/status-monitor "${PROJECT_ROOT}/scripts/status" temperature 15 &>> "${PROJECT_LOGS}/status-monitor.log" &
./scripts/status-monitor "${PROJECT_ROOT}/scripts/status" uptime 15 &>> "${PROJECT_LOGS}/status-monitor.log" &

for filename in "${STATUS_PATH}"/*; do
  ./scripts/status-monitor "${STATUS_PATH}" "$(basename "$filename")" 15 &>> "${PROJECT_LOGS}/status-monitor.log" &
done

echo "Starting API V1 manager..."
yarn start

echo "Pi Controller is now accessible at"
echo "  http://${DEVICE_HOSTNAME}"
echo "  http://${DEVICE_IP}"