#!/usr/bin/env bash
set -euo pipefail

# Start Pi Controller

check_dependencies () {
  for cmd in "$@"; do
    if ! command -v $cmd >/dev/null 2>&1; then
      echo "This script requires \"${cmd}\" to be installed"
      exit 1
    fi
  done
}

center() {
  termwidth="38"
  padding="$(printf '%0.1s' ={1..500})"
  printf '%*.*s %s %*.*s\n' 0 "$(((termwidth-2-${#1})/2))" "$padding" "$1" 0 "$(((termwidth-1-${#1})/2))" "$padding"
}

# Check system's dependencies
check_dependencies readlink dirname ip

# Check karen's dependencies
check_dependencies fswatch

# Check OTA update scripts' dependencies
check_dependencies rsync jq curl tr

# Check API V1 manager dependencies
check_dependencies yarn node nohup

PROJECT_ROOT="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.."
PROJECT_LOGS="${PROJECT_ROOT}/logs"

# Detect custom app
APP_PATH=""
APP_VERSION=""
APP_NAME=""
folders=(app/*)
if [ -d "${folders[0]}" ]; then
  APP_PATH="${folders[0]}"
  APP_VERSION=$(jq -r '.version' "${APP_PATH}/info.json")
  APP_NAME=$(jq -r '.name' "${APP_PATH}/info.json")
fi

echo
echo "======================================"
center "STARTING"
center "PI CONTROLLER"
echo "======================================"

if [[ -n "$APP_PATH" ]]; then
  echo "======================================"
  center "LOADED APP"
  center "${APP_NAME}"
  center "${APP_VERSION}"
  echo "======================================"
fi
echo

echo "Setting environment variables..."
echo

# Whitelist device IP, hostname and hidden service for CORS
DEVICE_IP="$(ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')"
DEVICE_HOSTNAME="$(hostname)"

cd "$PROJECT_ROOT"

echo "Starting karen..."
echo
./scripts/karen "${APP_PATH}"/events &>> "${PROJECT_LOGS}/karen.log" &

echo "Starting status monitors..."
pkill -f ./status-monitor || true
./scripts/status-monitor "${PROJECT_ROOT}/scripts/status" temperature 15 &>> "${PROJECT_LOGS}/status-monitor.log" &
./scripts/status-monitor "${PROJECT_ROOT}/scripts/status" uptime 15 &>> "${PROJECT_LOGS}/status-monitor.log" &

if [[ -n "$APP_PATH" ]]; then
  for filename in "${APP_PATH}"/status/*; do
    ./scripts/status-monitor "${APP_PATH}"/status "$(basename "$filename")" 15 &>> "${PROJECT_LOGS}/status-monitor.log" &
  done
fi

echo "Starting API V1 manager..."
yarn start

echo "Pi Controller is now accessible at"
echo "  http://${DEVICE_HOSTNAME}"
echo "  http://${DEVICE_IP}"