#!/usr/bin/env bash
set -euo pipefail

# Stop Pi Controller

PROJECT_ROOT="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.."

if [[ ! -d "$PROJECT_ROOT" ]]; then
  echo "Root dir does not exist '$PROJECT_ROOT'"
  exit 1
fi

# remove stuck signals
echo "Removing stuck signal files ..."
cd "$PROJECT_ROOT/scripts/events/signals"
rm -f ./*.signal

# TODO: Transition to pidfiles so we can reliably kill these processes
echo "Killing background services ..."
# shellcheck disable=SC2009
ps -Af \
  | grep '\./karen\|\./scripts/status-monitor\|pi_controller/scripts\|fswatch\|yarn\|bin/www' \
  | grep -v grep \
  | awk '{print $2}' \
  | xargs kill -9 2> /dev/null || true